<a href="https://colab.research.google.com/github/Akanerd/Orbit-Archieve/blob/main/Day%209%20-%20FGD%20Sesi%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Latihan 1**

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2],
              [3, 4],
              [0, 1]])
B = np.array([[4, 3],
              [2, 1]])
C = np.array([[1, 0],
              [2, 3]])

In [3]:
np.matmul(A,B)

array([[ 8,  5],
       [20, 13],
       [ 2,  1]])

In [ ]:
np.matmul(B,A)

In [5]:
np.matmul(B,C)

array([[10,  9],
       [ 4,  3]])

In [7]:
np.matmul(C,B)

array([[ 4,  3],
       [14,  9]])

In [10]:
m1 = np.matmul(A,B)
m2 = np.matmul(m1,C)
print(m2)

[[18 15]
 [46 39]
 [ 4  3]]


In [14]:
m3 = np.matmul(B,C)
m4 = np.matmul(A,m3)
print(m4)

[[18 15]
 [46 39]
 [ 4  3]]


# **Latihan 2**

In [ ]:
A = np.array([[0, 0],
              [4, 5]])
B = np.array([[4, 3],
              [2, 1]])


In [17]:
# 3 X A
A1 = np.array([[0, 0],
              [12, 15]])
# A X 3
A2 = np.array([[0, 0],
              [12, 15]])

In [ ]:
print(np.linalg.inv(A))

In [23]:
print(np.linalg.inv(B))

[[-0.5  1.5]
 [ 1.  -2. ]]


In [26]:
mb1 = np.linalg.inv(B)
mb3 = np.matmul(mb1,B)
print(mb3)

[[1. 0.]
 [0. 1.]]
