<a href="https://colab.research.google.com/github/Akanerd/Orbit-Archieve/blob/main/Day%2011%20-%20Live%20Code%20Sesi%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy arrays**

In [30]:
import numpy as np
# Membuat array
civilian_birth = np.array([4352,233,3245,256,2394])
civilian_birth

array([4352,  233, 3245,  256, 2394])

In [33]:
# special array dengan numpy dengan membuat matriks berisikan nilai nol
#Baris, kolom = 4,3
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.linspace(0,2,5) #dimulai dengan angka 0-1 yang kemudian memliki rentang sebanyak 2
                    #kemudian dibagi dengan 1/(hasil step)

array([0. , 0.5, 1. , 1.5, 2. ])

In [36]:
a = np.array([0,1])
b = np.array([2,3])
ab = np.stack((a, b)).T # Menggabungkan array
print(ab)

[[0 2]
 [1 3]]


# **Numpy Algebra with Numpy**


In [39]:
#(4x+ 5y = 23)
#(6x-3y = 3)

import numpy as np
A = np.array([[4,5],[6,-3]])
B = np.array([23, 3])
x,y = np.linalg.solve(A,B) # Mencari nilai x dan y
print("value dari x = ",x, "\nvalue dari y = ",y)

value dari x =  2.0 
value dari y =  3.0


In [41]:
matrix = np.matrix([[1,5,3],[9,5,6],[2,8,9]])
matrix.flatten()

matrix([[1, 5, 3, 9, 5, 6, 2, 8, 9]])

In [42]:
np.linalg.det(matrix) #Mencari nilai determinant

-162.00000000000009

In [48]:
matrix.diagonal().sum() # Mencari nilai rata-rata dari matriks

15

In [49]:
np.linalg.inv(matrix) # Mencari invers dari matriks

matrix([[ 0.01851852,  0.12962963, -0.09259259],
        [ 0.42592593, -0.01851852, -0.12962963],
        [-0.38271605, -0.01234568,  0.24691358]])

# **Pandas Series dan dataframe**

In [4]:
import pandas as pd

In [5]:
data = ['a','b','c','d']
s = pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
dtype: object


# **Pandas: Selection & Filtering**

In [6]:
data = {'name':['Jean','Robert','Lee','Jmaes'],'year':[2021,2014,2016,2001],'report':[3,2,4,12]}
index =['Melbourne', 'Texas', 'Berlin', 'Rome']
df = pd.DataFrame(data,index)
print(df)

             name  year  report
Melbourne    Jean  2021       3
Texas      Robert  2014       2
Berlin        Lee  2016       4
Rome        Jmaes  2001      12


# **Pandas : Data Transformation using Map**

In [12]:
data = {'name':['John J Jameson','Vera D Lynn','Martin J King','Iruma K Smith','Michale G Krupp'],
        'score':[6,7,3,9,7]}
df = pd.DataFrame(data)
df.T

0            1              2              3  \
name   John J Jameson  Vera D Lynn  Martin J King  Iruma K Smith   
score               6            7              3              9   

                     4  
name   Michale G Krupp  
score                7

In [25]:
def get_code(name):
  return "".join(k[0].upper() for k in name.split(' '))
df['code'] = df['name'].map(get_code)
df.T

0            1              2              3  \
name   John J Jameson  Vera D Lynn  Martin J King  Iruma K Smith   
score               6            7              3              9   
code              JJJ          VDL            MJK            IKS   

                     4  
name   Michale G Krupp  
score                7  
code               MGK

# **Data Aggregation: groupby**

In [52]:
import pandas as pd
data = {'name':['Jen','Max','Tina','John','Kay','Ish','Ami'],
        'year': [2012,2012,2013,2012,2013,2014,2014],
        'score': [4,5,9,8,9,5,4]}
df = pd.DataFrame(data)

#Menghitung tahu berdasarkan rata-rata score
df.groupby(['year'])['score'].mean()

year
2012    5.666667
2013    9.000000
2014    4.500000
Name: score, dtype: float64

# **Pandas: statiscal Analysis**

In [59]:
import pandas as pd
data = {'name':['Jason','Molly','Tina','Jake','Amy'],
        'age': [42,52,36,42,73],
        'score': [4,24,31,2,3]}
df = pd.DataFrame(data)
df.describe().T #Mencari statistik

count  mean        std   min   25%   50%   75%   max
age      5.0  49.0  14.594520  36.0  42.0  42.0  52.0  73.0
score    5.0  12.8  13.663821   2.0   3.0   4.0  24.0  31.0

In [60]:
print("Mean Of Score");print(df['score'].mean())
print("Median Of Score");print(df['score'].median())
print("Mode Of Age ");print(df['age'].mode())
print("Variance of Age");print(df['age'].var())
print("Skewness Of Age");print(df['age'].skew())

Mean Of Score
12.8
Median Of Score
4.0
Mode Of Age 
0    42
dtype: int64
Variance of Age
213.0
Skewness Of Age
1.4700997201463943


# **Pandas: Data Transformation Replacing Values**

In [61]:
import pandas as pd
data = {'name':['Jen K Frost','Max M Brown','Tina W Musk','John M Gates',
                'Kay W Carter','Ish T Sodhi'],
        'score': [4,5,9,8,9,5]}
df = pd.DataFrame(data)
df.T

0            1            2             3             4  \
name   Jen K Frost  Max M Brown  Tina W Musk  John M Gates  Kay W Carter   
score            4            5            9             8             9   

                 5  
name   Ish T Sodhi  
score            5

In [66]:
df.replace("Jen K Frost",'Jennifer K Forest',inplace=True)
df.T

0            1            2             3  \
name   Jennifer K Forest  Max M Brown  Tina W Musk  John M Gates   
score                  4            5            9             8   

                  4            5  
name   Kay W Carter  Ish T Sodhi  
score             9            5

# **Pandas: Data Transformation - Discretization & Binning**

In [67]:
import pandas as pd
data = {'name':['Jen','Max','Tina','John','Kay','Ish','Aml'],
        'year': [2012,2012,2013,2012,2013,2014,2014],
        'score': [4,5,9,8,9,5,4]}
df = pd.DataFrame(data)
                                    # bin 1 = 0 sampai 3, bin 2 = 3 sampaio 6, bin3 = 6 sampai 10
df['score_cat'] = pd.cut(df['score'],bins=[0,3,6,10],
                         labels=['Low','Medium','High'])
df.T

0       1     2     3     4       5       6
name          Jen     Max  Tina  John   Kay     Ish     Aml
year         2012    2012  2013  2012  2013    2014    2014
score           4       5     9     8     9       5       4
score_cat  Medium  Medium  High  High  High  Medium  Medium