<a href="https://colab.research.google.com/github/Akanerd/Orbit-Archieve/blob/main/Day%2014%20-%20FGD%20Live%20Code%20Sesi%202%20Naive%20Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from matplotlib.ticker import NullFormatter
import matplotlib.ticker as ticker
import itertools
from sklearn import preprocessing
from sklearn.datasets import load_iris
%matplotlib inline

In [2]:
outlook=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']
temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
humidity = ['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal','Normal','High','Normal','High']
windy = ['False','True','False','False','False','True','True','False','False','False','True','True','False','True']

play = ['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']


In [3]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

outlook_encoded=le.fit_transform(outlook)
temp_encoded=le.fit_transform(temp)
humidity_encoded=le.fit_transform(humidity)
windy_encoded=le.fit_transform(windy)

label = le.fit_transform(play)

In [4]:
print(outlook_encoded)
print(temp_encoded)
print(humidity_encoded)
print(windy_encoded)

print(label)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]
[0 0 0 0 1 1 1 0 1 1 1 0 1 0]
[0 1 0 0 0 1 1 0 0 0 1 1 0 1]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [5]:
features =np.column_stack([outlook_encoded,temp_encoded,humidity_encoded,windy_encoded])

In [6]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(features,label)

predict = model.predict([[0,2,0,1]])
print("Predicted Value",predict)

Predicted Value [1]
