<a href="https://colab.research.google.com/github/Akanerd/Orbit-Archieve/blob/main/Day%209%20-%20Live%20Code%20Sesi%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy dengan Python**

Import Library Numpy

In [1]:
import numpy as np

Inisialisasi Array dengan Numpy

In [2]:
a = np.array([1,3,5,9,11])
b = np.array([[1,3,5],[2,4,6],[7,7,9]])
c = np.array([[1,3],[2,4],[3,5],[4,6]])

print(a)
print(a.size)
print(a.ndim)
print(a.shape)
print(b)
print(b.size)
print(b.ndim)
print(b.shape)
print(c)
print(c.size)
print(c.ndim)
print(c.shape)

[ 1  3  5  9 11]
5
1
(5,)
[[1 3 5]
 [2 4 6]
 [7 7 9]]
9
2
(3, 3)
[[1 3]
 [2 4]
 [3 5]
 [4 6]]
8
2
(4, 2)


Slicing dengan Numpy

In [3]:
print(a[1:])
print(a[:4])

[ 3  5  9 11]
[1 3 5 9]


Indexing Array 2d dengan Numpy

In [6]:
print(b[0][2])
print(b[2,0])
print(b[0:,2])

5
7
[5 6 9]


# **Fundamental of Machine learning**


In [ ]:
print()