<a href="https://colab.research.google.com/github/Akanerd/Orbit-Archieve/blob/main/Day%206%20-%20NumPy%20Indexing%20and%20Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**NumPy Indexing and Selection**

In [ ]:
import numpy as np

In [ ]:
# Membuat sample array
arr = np.arange(0,11)
# show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#**Indexing**

In [ ]:
# Mendapatkan nilai pada indeks
arr[7]

7

In [ ]:
# Mendapatkan nilai pada range 1 hingga 5
# kenapa 5 tidak termasuk karena yang dipanggil adalah indeks 1 hingga indeks 
# sebelum 5
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

# **BroadCasting**

> Numpy arrays memiliki kemampuan untuk melakukan broadcast/ broadcasting



In [ ]:
# Menetapkan nilai dengan rentang indeks (contoh broadcast)
arr[0:5] = 100
#show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
# Mengatur ulang array
arr = np.arange(0,11)
# Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



> Data dicopy terdahulu agar memiliki backup untuk yang asli




In [ ]:
# Mendapatkan salinan (copy) dari array asli
ArrCopy = arr.copy()
ArrCopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Slicing 
SliceOfArray = arr[0:6]
# Menampilkan slice
SliceOfArray

array([0, 1, 2, 3, 4, 5])

In [ ]:
# Mengubah Slice 
SliceOfArray[:]=99
# Menampilkan Slice
SliceOfArray

array([99, 99, 99, 99, 99, 99])

In [ ]:
# Memanggil array asli kembali
# Terjadi peruahan pada array asli
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])